name: 'GMT Pytest'
description:  'Run Pytest with setup and teardown'
inputs:
  metrics-to-turn-off:
    description: 'a list of metrics to turn off that is passed to the disable metrics script'
    required: false
    default: ''
  gmt-directory:
    description: 'The root directory of the gmt repository'
    required: false
    default: '.'
  tests-command:
    description: 'The command to run the tests'
    required: false
    default: 'pytest'
  github-token:
    description: 'pass in your secrets.GITHUB_TOKEN'
    required: true

runs:
  using: 'composite'
  steps:
    - name: setup_python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - id: python_cache
      uses: actions/cache@v3
      with:
        path: venv
        key: pip-${{ steps.setup_python.outputs.python-version }}-${{ hashFiles('requirements.txt') }}-${{ hashFiles('requirements-dev.txt') }}-${{ hashFiles('metric_providers/psu/energy/ac/xgboost/machine/model/requirements.txt') }}

    # - name: Setup upterm session
    #   uses: lhotari/action-upterm@v1
      
    - name: Install docker for MacOS
      if: runner.os == 'macOS'
      shell: bash
      run: |
        brew install docker docker-compose
        mkdir -p ~/.docker/cli-plugins
        ln -sfn /usr/local/opt/docker-compose/bin/docker-compose ~/.docker/cli-plugins/docker-compose
        colima start --network-address

    - name: install script and packages
      if: runner.os == 'macOS'
      shell: bash
      working-directory: ${{ inputs.gmt-directory }}
      run: |
        ./install_mac.sh -p testpw -a http://api.green-coding.internal:9142 -m http://metrics.green-coding.internal:9142 
        source venv/bin/activate
        python3 -m pip install -r requirements-dev.txt
        python3 -m pip install -r metric_providers/psu/energy/ac/xgboost/machine/model/requirements.txt

    - name: Setup & Run Tests
      if: runner.os == 'macOS'
      shell: bash
      run: |
        source venv/bin/activate
        cd tests
        python3 setup-test-env.py
        ./start-test-containers.sh -d
        sleep 10
        cd stress-application
        docker build . -t gcb_stress_gmt_run_tmp
        cd ..
        python3 -m pytest -m "not no_mac_workflow" -rA | tee /tmp/test-results.txt

    - name: Display Results
      shell: bash
      if: always()
      run: |
        cat /tmp/test-results.txt | grep -oPz '(=*) short test summary(.*\n)*' >> $GITHUB_STEP_SUMMARY
