name: Pull Request Tests
run-name: PR check
on:
  pull_request:

jobs:
  run-tests:
    runs-on: macos-latest
    permissions:
      packages: write
      contents: read
      pull-requests: write
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          submodules: 'true'

      - name: 'Setup, Run, and Teardown Tests'
        uses: ./.github/actions/gmt-pytest
        with:
         metrics-to-turn-off: '--categories RAPL Machine Sensors Debug CGroupV2 MacOS'
         github-token: ${{ secrets.GITHUB_TOKEN }}
